version: '2.1'
services:
  selenium:
    image: selenium/hub:3.10.0
    ports:
      - "4444:4444"

  firefox:
    image: selenium/node-firefox:2.53.0
    privileged: true
    depends_on:
      - selenium
    ports:
      - "5900:5900"
    environment:
      - no_proxy=localhost
      - HUB_PORT_4444_TCP_ADDR=selenium
      - HUB_PORT_4444_TCP_PORT=4444

  magento:
    image: pagarme/magento2 
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - .:/var/www/html/app/modules
  db:
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 1s
      retries: 20
    image: mysql:5.6.23
    volumes:
      - db-data:/var/lib/mysql/data
    env_file:
      - .env
volumes:
  db-data:
